import { useState } from 'react'
import { useReindex, useTriggerIssue, useCancelJobs, useStatus, useSaveSettings } from '../../api/queries'
import { EditorialPrompts } from './EditorialPrompts'
import { color } from '../../theme/tokens'
import type { Settings } from '../../types/settings'

function btnStyle(disabled: boolean): React.CSSProperties {
  return { background: 'transparent', border: `1px solid ${color.dark}`, borderRadius: 5,
    padding: '10px 18px', fontSize: 14, color: color.inkStrong, cursor: disabled ? 'default' : 'pointer',
    opacity: disabled ? 0.5 : 1, fontFamily: "'Newsreader', Georgia, serif" }
}
const cancelStyle: React.CSSProperties = { marginLeft: 12, background: 'transparent',
  border: `1px solid ${color.accent}`, borderRadius: 5, padding: '9px 14px', fontSize: 13,
  color: color.accent, cursor: 'pointer', fontFamily: "'Newsreader', Georgia, serif" }

export function AdvancedPanel({ noteCount, settings }: { noteCount: number; settings: Settings }) {
  const reindex = useReindex()
  const generate = useTriggerIssue()
  const cancel = useCancelJobs()
  const save = useSaveSettings()
  const [interval, setInterval_] = useState(settings.sync_interval_minutes)
  function saveInterval() {
    const n = Math.trunc(Number(interval) || 0)
    const clamped = n <= 0 ? 0 : Math.max(30, n)   // 0 = off, else >= 30
    setInterval_(clamped)
    save.mutate({ sync_interval_minutes: clamped })
  }
  // Poll status while the Settings page is open so the buttons reflect job
  // state (disable while running, re-enable when done) within a couple seconds.
  const status = useStatus({ refetchInterval: 2500 })
  const active = status.data?.active_jobs ?? []
  const reindexing = active.includes('ingest') || active.includes('cluster')
  const generating = active.includes('generate')
  const indexed = status.data?.indexed ?? false   // themes/embeddings exist → can compose a real edition
  const themeCount = status.data?.theme_count      // themes generated by the last clustering pass

  function cancelReindex() {
    cancel.mutate('ingest'); cancel.mutate('cluster')
  }

  return (
    <div style={{ padding: '28px 0', borderBottom: `1px solid ${color.border}` }}>
      <div style={{ fontSize: 11, letterSpacing: '.18em', textTransform: 'uppercase', color: color.faint, fontWeight: 600 }}>Advanced</div>
      <div style={{ marginTop: 18, display: 'flex', flexDirection: 'column', gap: 20 }}>
        <div>
          <button type="button" disabled={reindexing || reindex.isPending} style={btnStyle(reindexing || reindex.isPending)}
            onClick={() => reindex.mutate(false)}>Re-index notes &amp; embeddings</button>
          {reindexing && <button type="button" style={cancelStyle} onClick={cancelReindex}>Cancel</button>}
          {reindexing && <span style={{ marginLeft: 12, fontSize: 14, color: color.muted, fontStyle: 'italic' }}>Re-indexing…</span>}
          {reindex.isError && <span style={{ marginLeft: 12, fontSize: 14, color: color.accent }}>Couldn't queue — is a notes folder set?</span>}
          <p style={{ fontSize: 14, lineHeight: 1.55, color: color.muted, marginTop: 8 }}>
            Reads your notes folder, refreshes summaries + embeddings, and re-composes your themes. {noteCount} notes
            {themeCount != null && ` · ${themeCount} ${themeCount === 1 ? 'theme' : 'themes'}`}.
          </p>
        </div>
        <div>
          <button type="button" disabled={generating || generate.isPending || !indexed}
            style={btnStyle(generating || generate.isPending || !indexed)}
            onClick={() => generate.mutate()}>Generate an issue now</button>
          {generating && <button type="button" style={cancelStyle} onClick={() => cancel.mutate('generate')}>Cancel</button>}
          {generating && <span style={{ marginLeft: 12, fontSize: 14, color: color.muted, fontStyle: 'italic' }}>Composing…</span>}
          {status.data && !indexed && !generating && (
            <p style={{ fontSize: 13, color: color.faint, marginTop: 8, fontStyle: 'italic' }}>
              Generate embeddings first — run “Re-index notes &amp; embeddings” above.
            </p>
          )}
        </div>
        <div>
          <label htmlFor="sync-interval" style={{ fontSize: 14, color: color.muted }}>Auto-sync every (minutes, 0 = off, min 30)</label>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center', marginTop: 6 }}>
            <input id="sync-interval" aria-label="auto-sync every" type="number" min={0} step={1} value={interval}
              onChange={(e) => setInterval_(Math.trunc(+e.target.value))} onBlur={saveInterval}
              style={{ width: 90, background: color.card, border: `1px solid ${color.borderStrong}`,
                borderRadius: 5, padding: '8px 10px', fontSize: 14, color: color.inkStrong }} />
            <span style={{ fontSize: 13, color: color.faint }}>{interval === 0 ? 'off' : `every ${interval} min`}</span>
          </div>
        </div>
      </div>
      <EditorialPrompts settings={settings} />
    </div>
  )
}
